In [1]:
import datetime
import pandas as pd
import time
import requests
import os

API_KEY = "_T8YnZaxCVsyj_AKsnus"

URL_TEMPLATE = "https://www.quandl.com/api/v3/datasets/EOD/{0}.csv?api_key={1}"
URL_TEMPLATE = "https://www.quandl.com/api/v3/datatables/WIKI/PRICES?date.gte={}&date.lt={}&ticker={}&api_key={}"

START_DATE = "2000-01-01"
END_DATE = "2017-11-01"

In [2]:
dj_components = [
    "DD",
    "UNH",
    "CSCO",
    "HD",
    "JNJ",
    "PG",
    "GE",
    "TRV",
    "AXP",
    "MRK",
    "NKE",
    "MSFT",
    "UTX",
    "PFE",
    "GS",
    "V",
    "IBM",
    "JPM",
    "WMT",
    "XOM",
    "KO",
    "MMM",
    "MCD",
    "CAT",
    "INTC",
    "DIS",
    "BA",
    "AAPL",
    "CVX",
    "VZ"
]

directory = "djia_20000101_20171101"

In [3]:

if not os.path.exists(directory):
    os.makedirs(directory)

for ticker in dj_components:
    url = URL_TEMPLATE.format(START_DATE, END_DATE, ticker, API_KEY)
    r = requests.get(url).json()
    col_names = [c["name"] for c in r["datatable"]["columns"]]
    df = pd.DataFrame(r["datatable"]["data"], columns = col_names)
    
    df = df[((df.date >= START_DATE) & (df.date <= END_DATE))]
    df = df[["date", "adj_open", "adj_high", "adj_low", "adj_close", "adj_volume"]]
    df.to_csv("{}/{}.csv".format(directory, ticker.lower()), index=False)

In [4]:
df

            date   adj_open   adj_high    adj_low  adj_close  adj_volume
0     2000-01-03  24.490002  24.893928  24.086077  24.211294   4663700.0
1     2000-01-04  24.110312  24.413256  23.124734  23.427678   5005800.0
2     2000-01-05  23.831604  24.562709  23.629641  24.211294   6368500.0
3     2000-01-06  24.266978  24.266978  23.734398  24.088096   4705600.0
4     2000-01-07  23.937673  24.010852  23.502664  23.909214   5043800.0
5     2000-01-10  23.909214  24.112489  23.502664  23.783184   4487800.0
6     2000-01-11  23.478271  23.734398  23.274996  23.559581   3694400.0
7     2000-01-12  22.921297  23.429485  22.766808  22.766808   4288100.0
8     2000-01-13  23.173359  23.250603  22.587926  22.587926   3783700.0
9     2000-01-14  22.742415  23.022935  22.587926  22.892839   3180500.0
10    2000-01-18  23.173359  24.368616  23.096114  23.884821   4861700.0
11    2000-01-19  23.376634  23.783184  23.376634  23.429485   2962300.0
12    2000-01-20  23.604302  24.088096  23.502664  23.502664   2711000.0
13    2000-01-21  24.344223  24.925590  23.986459  24.417402   5706500.0
14    2000-01-24  24.519040  24.722315  24.368616  24.445861   3908300.0
15    2000-01-25  24.417402  24.494647  23.657153  23.783184   4420200.0
16    2000-01-26  23.884821  23.962066  23.401027  23.478271   4054100.0
17    2000-01-27  23.579909  23.884821  23.226210  23.681546   3124900.0
18    2000-01-28  23.555516  23.937673  23.197752  23.429485   3357400.0
19    2000-01-31  23.401027  25.612659  23.197752  25.181716   5373000.0
20    2000-02-01  24.697922  24.954048  24.088096  24.214127   4674000.0
21    2000-02-02  24.417402  24.445861  24.039310  24.112489   2948400.0
22    2000-02-03  24.291371  24.445861  23.579909  23.758791   2589900.0
23    2000-02-04  23.884821  24.266978  23.705939  23.807577   3401800.0
24    2000-02-07  23.807577  24.368616  23.555516  24.291371   3313900.0
25    2000-02-08  24.315764  24.596284  23.860428  23.986459   3069200.0
26    2000-02-09  23.986459  24.063703  23.376634  23.502664   3224600.0
27    2000-02-10  23.453878  23.478271  23.124573  23.197752   2851600.0
28    2000-02-11  23.148966  23.173359  22.132590  22.766808   3436700.0
29    2000-02-14  22.766808  22.892839  22.311472  22.486289   2905400.0
...          ...        ...        ...        ...        ...         ...
4457  2017-09-20  49.300000  49.640000  49.080000  49.480000  18364373.0
4458  2017-09-21  49.370000  49.440000  48.844000  48.940000  14272748.0
4459  2017-09-22  49.190000  50.080000  49.020000  49.900000  20502636.0
4460  2017-09-25  49.870000  50.315000  49.745000  49.900000  13197167.0
4461  2017-09-26  49.960000  50.080000  49.400000  49.510000  10678869.0
4462  2017-09-27  49.190000  49.725000  49.120000  49.510000  13699541.0
4463  2017-09-28  49.240000  49.565000  49.140100  49.410000   8123980.0
4464  2017-09-29  49.300000  49.830000  49.010000  49.490000  12677001.0
4465  2017-10-02  49.390000  49.700000  49.250000  49.360000   9318056.0
4466  2017-10-03  49.450000  50.020000  49.430000  49.850000  10172423.0
4467  2017-10-04  49.640000  50.080000  49.380000  49.900000   9844644.0
4468  2017-10-05  49.960000  50.034500  49.675000  49.770000  12220774.0
4469  2017-10-06  49.040000  49.200000  48.655500  48.810000  13166820.0
4470  2017-10-09  48.890000  49.090000  48.650000  49.050000  10693747.0
4471  2017-10-10  49.280000  49.490000  49.055000  49.140000  10249882.0
4472  2017-10-11  49.140000  49.320000  48.510000  48.860000  10057490.0
4473  2017-10-12  48.440000  48.850000  48.130000  48.350000  16723138.0
4474  2017-10-13  48.340000  48.480000  47.830000  47.860000  19938102.0
4475  2017-10-16  47.900000  48.350000  47.700000  48.090000  10382351.0
4476  2017-10-17  48.090000  48.490000  47.870000  48.400000  13551892.0
4477  2017-10-18  48.330000  48.850000  47.760000  48.650000  20346013.0
4478  2017-10-19  50.050000  51.180000  49.050000  49.210000  28651656.0
4479  2017-10-20  49.450000  49.590000  48.930000  49.530000  15963778.0
4480  2017-10-23  49.470000  49.690000  48.910000  48.990000  15615573.0
4481  2017-10-24  49.160000  49.280000  48.720000  48.940000  11323112.0
4482  2017-10-25  48.680000  48.790000  48.150000  48.665000  17399314.0
4483  2017-10-26  48.860000  49.430000  48.750000  48.890000  14261705.0
4484  2017-10-27  48.720000  49.387500  48.530000  48.870000  12376736.0
4485  2017-10-30  48.880000  49.120000  47.420000  47.830000  24530229.0
4486  2017-10-31  47.940000  48.180000  47.710000  47.870000  15503967.0

[4487 rows x 6 columns]